/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualanmotorbekas;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import static penjualanmotorbekas.formidentitasmotor.tombolbatal;
import static penjualanmotorbekas.formidentitasmotor.tombolubah;
import static penjualanmotorbekas.formidentitasmotor.tombolhapus;
import static penjualanmotorbekas.formidentitasmotor.tombolsimpan;
import static penjualanmotorbekas.formmenu.btnCustomer;
import static penjualanmotorbekas.formmenu.btnIdentitasMotor;
import static penjualanmotorbekas.formmenu.btnuser;
import static penjualanmotorbekas.formuser.tombolBatal;
import static penjualanmotorbekas.formuser.tombolUbah;
import static penjualanmotorbekas.formmenu.btnTransaksi;
import static penjualanmotorbekas.formmenu.lihatBarang;
import static penjualanmotorbekas.formmenu.lihatDaftarTransaksiPenjualan;
import static penjualanmotorbekas.formtransaksi.btnDaftarBarang;
import static penjualanmotorbekas.formtransaksi.btnTransaksiPenjualan;
import static penjualanmotorbekas.formuser.tombolHapus;
import static penjualanmotorbekas.formuser.tombolSimpan;
import static penjualanmotorbekas.transaksi_penjualan.bBatal;
import static penjualanmotorbekas.transaksi_penjualan.bHapus;
import static penjualanmotorbekas.transaksi_penjualan.bSimpan;
import static penjualanmotorbekas.transaksi_penjualan.bUbah;


                                        /*
                                         RIDA ARMEILIA      1910631170123
                                         IDE NABILLA AUDY   1910631170023
                                         MAYA MAESAROH      1910631170028
                                         FARHAN ASSEGAF     1910631170019

                                                    5D TEKNIK INFORMATIKA
                                         */
/**
 *
 * @author ASUS
 */
public class formlogin extends javax.swing.JFrame {
    
            formmenu a;
    /**
     * Creates new form formlogin
     */
    public formlogin() {
        initComponents();
        
        a = new formmenu();
        a.setVisible(false);
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtuser = new javax.swing.JTextField();
        cbuser = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnlogin = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        txtuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtuserKeyPressed(evt);
            }
        });

        cbuser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Hak Akses", "Pemilik", "Teller", "Teknisi", "Customer" }));
        cbuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbuserActionPerformed(evt);
            }
        });
        cbuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbuserKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel3.setText("ID User");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel6.setText("Welcome!");

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel4.setText("Password");

        btnlogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/login_1.png"))); // NOI18N
        btnlogin.setText("LOGIN");
        btnlogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnloginActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/login.png"))); // NOI18N
        jLabel5.setText("Username");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
        jLabel8.setText("Please insert your ID User and Password");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbuser, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(131, 131, 131))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(31, 31, 31)
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(249, 249, 249))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(cbuser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtuserKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            txtpass.requestFocus();
        }
    }//GEN-LAST:event_txtuserKeyPressed

    private void cbuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbuserActionPerformed

    private void cbuserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbuserKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnlogin.requestFocus();
        }
    }//GEN-LAST:event_cbuserKeyPressed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void btnloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnloginActionPerformed
        // TODO add your handling code here:
        if(txtuser.getText().equals("") && txtpass.getText().equals("") && cbuser.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "iduser and password required !!");
        }
        else{
            try {
                java.sql.Connection conn = (java.sql.Connection) koneksi.getKoneksi();
                java.sql.Statement stm = conn.createStatement();
                java.sql.ResultSet sql = stm.executeQuery("select * from user where iduser='" + txtuser.getText() + "' "
                    +"and password = '" + txtpass.getText()
                    +"' and hak_akses='"+cbuser.getSelectedItem()+"'");

                sql.last();

                if (txtuser.getText().equals("iduser") && txtpass.getText().equals("password") && cbuser.getSelectedItem().equals("hak_akses")){
                    JOptionPane.showMessageDialog(null, "Selamat Anda Berhasil Login!");
                    this.dispose();

                }else if(sql.getRow()>=1){
                    if(cbuser.getSelectedItem().equals("Pemilik")){
                        JOptionPane.showMessageDialog(null, "Berhasil Login sebagai Pemilik!");
                        a.setVisible(true);
                        //Mengatur hak akses pemilik
                        lihatBarang.setEnabled(true);
                        lihatDaftarTransaksiPenjualan.setEnabled(false);
                        
                        //Bisa melihat daftar barang
                        btnDaftarBarang.setEnabled(true);
                        
                        //Mengatur agar menu transaksi penjualan tidak dapat diakses oleh pemilik
                        btnTransaksiPenjualan.setEnabled(false);

                        //Mengatur hak akses menu identitas motor
                        btnIdentitasMotor.setEnabled(true);
                        tombolsimpan.setEnabled(true);
                        tombolhapus.setEnabled(true);
                        tombolubah.setEnabled(true);
                        tombolbatal.setEnabled(true);

                        //Mengatur hak akses menu customer
                        btnCustomer.setEnabled(true);

                        //Mengatur menu transaksi agar tidak dapat di crud oleh pemilik
                        btnTransaksi.setEnabled(true);
                        bSimpan.setEnabled(false);
                        bUbah.setEnabled(false);
                        bBatal.setEnabled(false);
                        bHapus.setEnabled(false);

                        //Mengatur hak akses menu form user untuk pemilik
                        btnuser.setEnabled(true);
                        tombolSimpan.setEnabled(true);
                        tombolBatal.setEnabled(true);
                        tombolHapus.setEnabled(true);
                        tombolUbah.setEnabled(true);

                        txtuser.setText("");
                        txtpass.setText("");
                        cbuser.setSelectedItem("Pemilik");
                        this.dispose();

                        //Mengatur hak akses Teller
                    }else if(cbuser.getSelectedItem().equals("Teller")){
                        JOptionPane.showMessageDialog(null, "Berhasil Login sebagai Teller!");

                        a.setVisible(true);
                        //Mengatur hak akses menu identitas motor
                        btnIdentitasMotor.setEnabled(false);

                        //Mengatur hak akses menu customer
                        btnCustomer.setEnabled(true);

                        //Mengatur hak akses menu transaksi untuk teller
                        btnTransaksiPenjualan.setEnabled(true);
                        btnTransaksi.setEnabled(true);
                        bSimpan.setEnabled(true);
                        bUbah.setEnabled(true);
                        bBatal.setEnabled(true);
                        bHapus.setEnabled(true);

                        lihatBarang.setEnabled(true);
                        lihatDaftarTransaksiPenjualan.setEnabled(true);

                        // Mengatur hak akses menu form user
                        btnuser.setEnabled(true);
                        tombolSimpan.setEnabled(true);
                        tombolBatal.setEnabled(true);
                        tombolHapus.setEnabled(false);
                        tombolUbah.setEnabled(false);

                        txtuser.setText("");
                        txtpass.setText("");
                        cbuser.setSelectedItem("Teller");
                        this.dispose();

                        //Mengatur hak akses Teknisi
                    }else if(cbuser.getSelectedItem().equals("Teknisi")){
                        JOptionPane.showMessageDialog(null, "Berhasil Login sebagai Teknisi!");
                        a.setVisible(true);
                        //Mengatur hak akses menu form user
                        btnuser.setEnabled(false);

                        //Mengatur hak akses menu identitas motor
                        btnIdentitasMotor.setEnabled(false);

                        //Mengatur hak akses menu costumer
                        btnCustomer.setEnabled(true);

                        //Mengatur hak akses menu transaksi
                        btnTransaksi.setEnabled(true);

                        //Mengatur hak akses menu daftar barang
                        btnDaftarBarang.setEnabled(false);
                        
                        //Mengatur hak akses menu transaksi penjualan
                        btnTransaksiPenjualan.setEnabled(true);
                        bSimpan.setEnabled(false);
                        bHapus.setEnabled(true);
                        bUbah.setEnabled(false);
                        bBatal.setEnabled(true);
                       
                        lihatBarang.setEnabled(true);
                        lihatDaftarTransaksiPenjualan.setEnabled(true);

                        txtuser.setText("");
                        txtpass.setText("");
                        cbuser.setSelectedItem("Teknisi");
                        this.dispose();

                        //Mengatur hak akses Customer
                    }else if(cbuser.getSelectedItem().equals("Customer")){
                        JOptionPane.showMessageDialog(null, "Berhasil Login sebagai Customer!");
                        a.setVisible(true);
                        // hak akses menu transaksi
                        btnTransaksi.setEnabled(false);

                        //hak akses menu daftar barang
                        btnDaftarBarang.setEnabled(false);

                        //hak akses menu user
                        btnuser.setEnabled(false);

                        //hak akses menu customer
                        btnCustomer.setEnabled(true);

                        //hak akses menu identitas motor
                        btnIdentitasMotor.setEnabled(false);
                        
                        lihatDaftarTransaksiPenjualan.setEnabled(true);
                        lihatBarang.setEnabled(true);
                        bSimpan.setEnabled(false);
                        bUbah.setEnabled(false);
                        bBatal.setEnabled(false);
                        bHapus.setEnabled(false);

                        txtuser.setText("");
                        txtpass.setText("");
                        cbuser.setSelectedItem("Customer");
                        this.dispose();

                    } else if(sql.getRow() ==0) {
                        JOptionPane.showMessageDialog(null, "Gagal Login! Periksa Kembali ID User dan Password!");
                        txtuser.setText("");
                        txtpass.setText("");
                        txtuser.requestFocus();
                    }
                    stm.close();
                }
            } catch (SQLException e) {
            }
        }
        }

        /* private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
        }

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
            // TODO add your handling code here:
            if (JOptionPane.showConfirmDialog(null, "Yakin ingin keluar?", "penjualan motor bekas", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                this.setVisible(false);
            }
    }//GEN-LAST:event_btnloginActionPerformed
*/
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setState(1);
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogin;
    private javax.swing.JComboBox<String> cbuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
